{
 "title": "DDB Access",
 "tags": [ "mlrd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table_name",
    "label": "Table",
    "query": {
     "query": "label_values(req_table_total, table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (table_name) (t_ddb_read_max{table_name=~\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by (table_name) (t_ddb_read_p99{table_name=~\"$table_name\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "max by (table_name) (t_ddb_read_p50{table_name=~\"$table_name\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Write Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (table_name) (t_ddb_write_max{table_name=~\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by (table_name) (t_ddb_write_p99{table_name=~\"$table_name\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "max by (table_name) (t_ddb_write_p50{table_name=~\"$table_name\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "GetItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_get_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "PutItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_put_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Query",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_query_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "UpdateItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_update_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Scan",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_scan_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "DeleteItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_delete_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "BatchGetItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_batch_get_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "BatchWriteItem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(ddb_batch_write_item_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Control",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ddb_ctrl_total[$__rate_interval]))",
     "legendFormat": "control"
    }
   ]
  },
  {
   "title": "Forward",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ddb_fwd_total[$__rate_interval]))",
     "legendFormat": "forward"
    }
   ]
  }
 ]
}