{
 "title": "SQL Access",
 "tags": [ "mlrd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table_name",
    "label": "Table",
    "query": {
     "query": "label_values(req_table_total, table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (table_name) (t_sql_read_max{table_name=~\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by (table_name) (t_sql_read_p99{table_name=~\"$table_name\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "max by (table_name) (t_sql_read_p50{table_name=~\"$table_name\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Write Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (table_name) (t_sql_write_max{table_name=~\"$table_name\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by (table_name) (t_sql_write_p99{table_name=~\"$table_name\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "max by (table_name) (t_sql_write_p50{table_name=~\"$table_name\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_read_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_write_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "%Read Nop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_read_nop_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_read_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%read_nop"
    }
   ]
  },
  {
   "title": "Read Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_read_snapshot_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Read Cond",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_read_cond_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_insert_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Update",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_update_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_delete_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Upsert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_upsert_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "%Delete Nop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_delete_nop_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_delete_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%delete_nop"
    }
   ]
  },
  {
   "title": "Scan Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval]))",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "%Scan Index",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_index_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_index"
    }
   ]
  },
  {
   "title": "%Scan Filter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_filter_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_filter"
    }
   ]
  },
  {
   "title": "%Scan Key",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_key_cond_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_key"
    }
   ]
  },
  {
   "title": "%Scan Nop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_nop_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_nop"
    }
   ]
  },
  {
   "title": "%Scan Page",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_page_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_page"
    }
   ]
  },
  {
   "title": "%Scan Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (table_name) (rate(sql_scan_count_total{table_name=~\"$table_name\"}[$__rate_interval])) / sum by (table_name) (rate(sql_scan_total{table_name=~\"$table_name\"}[$__rate_interval])) * 100",
     "legendFormat": "%scan_count"
    }
   ]
  }
 ]
}